import type { Metadata } from "next";
import localFont from "next/font/local"; // Make sure to import `localFont` for local fonts.
import { Barlow_Condensed } from "next/font/google"; // Correct import for Google Fonts.
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const barlowCondensed = Barlow_Condensed({
  weight: ["300", "400", "500", "600", "700", "800"], // Corrected weight values
  subsets: ["latin"], // Corrected subsets array
});

export const metadata: Metadata = {
  title: "Burger | A healthy Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${barlowCondensed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
